server:
  port: 3344
spring:
  application:
    name: cloud-center-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LCY529-gcs/springcloud-config.git
          search-paths:
            - springcloud-config
          username: LCY529-gcs
          password: lvchangyu5290..
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
