server:
  port: 3344
spring:
  application:
    name: cloud-center-config
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:chang_yu_lu/spring_cloud_test.git
          search-paths:
            - spring_cloud_test
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
