server:
  port: 8005
spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      host: 192.168.193.130
      port: 8500
      discovery:
        service-name: ${spring.application.name}